name: Auto update commit hash

on:
  push:
    branches:
      - main

jobs:
  update-commit-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Get latest commit hash
        id: get-hash
        run: |
          echo "commit_hash=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout antifake-web-ui
        uses: actions/checkout@v4
        with:
          repository: UoA-CSS-Lab/antifake-web-ui
          token: ${{ secrets.REPO_WEBUI_PAT }}
          path: antifake-web-ui
          fetch-depth: 0
        
      - name: Update package-lock.json
        working-directory: antifake-web-ui
        run: |
          chmod +x ./reload_scatter.sh
          ./reload_scatter.sh

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.REPO_WEBUI_PAT }}
          path: antifake-web-ui
          commit-message: "chore: update deepscatter to ${{ steps.get-hash.outputs.commit_hash }}"
          branch: update-deepscatter-${{ steps.get-hash.outputs.commit_hash }}
          title: "Update deepscatter to latest commit"
          body: |
            This PR updates deepscatter to commit ${{ steps.get-hash.outputs.commit_hash }}

            Auto-generated by GitHub Actions
            Source: ${{ github.event.head_commit.url }}
