name: Auto update commit hash
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-commit-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit info
        id: commit
        run: |
          echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "repo=${{ github.repository }}" >> $GITHUB_OUTPUT
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Checkout antifake-web-ui
        uses: actions/checkout@v4
        with:
          repository: UoA-CSS-Lab/antifake-web-ui
          token: ${{ secrets.REPO_WEBUI_PAT }}
        
      - name: Update deepscatter
        run: |
          # package.jsonを確認
          cat package.json | grep deepscatter || true
          
          # 明示的にdeepscatterを最新コミットに更新
          npm install git+https://github.com/UoA-CSS-Lab/deepscatter.git#${{ steps.commit.outputs.sha }} --save
          
          # または既存のスクリプトを使用
          # rm -rf node_modules/deepscatter
          # rm ./package-lock.json
          # npm i
          
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.REPO_WEBUI_PAT }}
          commit-message: "chore: update deepscatter to ${{ steps.commit.outputs.sha }}"
          branch: update-deepscatter-${{ steps.commit.outputs.sha }}
          title: "Update deepscatter to latest commit"
          body: |
            This PR updates deepscatter to commit ${{ steps.commit.outputs.sha }}
            Auto-generated by GitHub Actions
            Source: ${{ github.server_url }}/${{ steps.commit.outputs.repo }}/commit/${{ steps.commit.outputs.sha }}
